version: "3.3"

services:
  www:
    image: gcr.io/jblewpl-kube/jblewplold-web
    ports:
      - "8002:80"
    links:
      - db
    networks:
      - default
  db:
    image: gcr.io/jblewpl-kube/jblewplold-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jblew_jblew
      MYSQL_USER: jblew_jblew
      MYSQL_PASSWORD: jblew_jblew
      MYSQL_ROOT_PASSWORD: jblew_jblew
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - default
