apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: jblewpl_website
spec:
  selector:
    matchLabels:
      app: jblewpl_website
      tier: db
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: jblewpl_website
        tier: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: jblew_jblew
            - name: MYSQL_PASSWORD
              value: jblew_jblew
            - name: MYSQL_ROOT_PASSWORD
              value: jblew_jblew
            - name: MYSQL_USER
              value: jblew_jblew
          image: gcr.io/jblewpl-kube/jblewplold-db
          name: db
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: jblewpl_website
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: jblewpl_website
    tier: db
