apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jblewpl-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: jblewpl-addr
spec:
  backend:
    serviceName: jblewplold-backend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jblewplold-backend
  labels:
    app: jblewpl
spec:
  type: NodePort
  selector:
    app: jblewpl_website
    tier: www
  ports:
    - port: 80
      targetPort: 80
