apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jblewpl-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: jblewpl-addr
  labels:
    app: jblewpl_website
spec:
  backend:
    serviceName: jblewpl-website-backend
    servicePort: 8080
