apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: www
  name: www
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.kompose.service: www
    spec:
      containers:
        - image: gcr.io/jblewpl-kube/jblewplold-web
          name: www
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: www
  name: www
spec:
  ports:
    - name: "80"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: www
status:
  loadBalancer: {}
