apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: jblewpl_website
spec:
  selector:
    matchLabels:
      app: jblewpl_website
      tier: www
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: jblewpl_website
        tier: www
    spec:
      containers:
        - image: gcr.io/jblewpl-kube/jblewplold-web
          name: www
          ports:
            - containerPort: 80
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jblewpl-website-backend
  labels:
    app: jblewpl_website
spec:
  type: NodePort
  selector:
    app: jblewpl_website
    tier: www
  ports:
    - port: 8080
      targetPort: 80
